language: shell

dist: xenial
addons:
  apt:
    packages:
    - realpath

jobs:
  fast_finish: true
  include:
   # Libraries
   - stage: "Libraries"
     env:
     - PACKAGE=lib/usb

   - stage: "Libraries"
     env:
     - PACKAGE=lib/ftdi

   - stage: "Libraries"
     env:
     - PACKAGE=lib/xml2

   # OSX
   - stage: "Libraries"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=lib/usb

   - stage: "Libraries"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=lib/ftdi

   - stage: "Libraries"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=lib/xml2

   # Windows
   - stage: "Libraries"
     os: windows
     env:
     - PACKAGE=lib/usb

   - stage: "Libraries"
     os: windows
     env:
     - PACKAGE=lib/ftdi

   # Programming Tools
   - stage: "Programming Tools"
     env:
     - PACKAGE=prog/iceprog

   - stage: "Programming Tools"
     env:
     - PACKAGE=prog/icefunprog

   - stage: "Programming Tools"
     env:
     - PACKAGE=prog/openocd

   - stage: "Programming Tools"
     env:
     - PACKAGE=prog/flterm

   - stage: "Programming Tools"
     env:
     - PACKAGE=prog/fxload

   - stage: "Programming Tools"
     env:
     - PACKAGE=prog/dfu-util

   # OSX
   - stage: "Programming Tools"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=prog/iceprog

   - stage: "Programming Tools"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=prog/icefunprog

   - stage: "Programming Tools"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=prog/dfu-util

   - stage: "Programming Tools"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=prog/openocd

   - stage: "Programming Tools"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=prog/flterm

   # Windows
   - stage: "Programming Tools"
     os: windows
     env:
     - PACKAGE=prog/iceprog

before_install:
 - source $TRAVIS_BUILD_DIR/.travis/common.sh
 - bash $TRAVIS_BUILD_DIR/.travis/fixup-git.sh
 - bash $TRAVIS_BUILD_DIR/.travis/download_sdk.sh
 - source $TRAVIS_BUILD_DIR/.travis/common.sh

install:
 - bash $TRAVIS_BUILD_DIR/.travis/install.sh

script:
 - bash $TRAVIS_BUILD_DIR/.travis/script.sh

after_failure:
 - bash $TRAVIS_BUILD_DIR/.travis/after_failure.sh

after_success:
 - bash $TRAVIS_BUILD_DIR/.travis/after_success.sh

cache:
  directories:
   - $HOME/.conda/pkgs
