language: shell

dist: xenial
addons:
  apt:
    packages:
    - realpath

stages:
  - name: "No dependencies" # Doesn't depend on anything apart from upstream packages
    if: type != cron
  - name: "Has first level dependencies" # Depends on a package in the "no dependencies" group
    if: type != cron
  - name: "Has second level dependencies" # Depends on a package in the "Has first level dependencies" group
    if: type != cron
  - name: "Main label upload" # Puts Anaconda packages to the main label
    if: type = push AND branch = master
  - name: "Cleanup" # Job for removing old Anaconda labels
    if: type = cron

jobs:
  fast_finish: true
  include:
   - stage: "No dependencies"
     env:
     - PACKAGE=lib/usb

   - stage: "No dependencies"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=lib/usb

   - stage: "No dependencies"
     os: windows
     env:
     - PACKAGE=lib/usb

   - stage: "No dependencies"
     env:
     - PACKAGE=lib/xml2

   - stage: "No dependencies"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=lib/xml2

   - stage: "No dependencies"
     env:
     - PACKAGE=tools/icefunprog

   - stage: "No dependencies"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=tools/icefunprog

   - stage: "No dependencies"
     env:
     - PACKAGE=tools/flterm

   - stage: "No dependencies"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=tools/flterm


   - stage: "Has first level dependencies"
     env:
     - PACKAGE=lib/ftdi

   - stage: "Has first level dependencies"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=lib/ftdi

   - stage: "Has first level dependencies"
     os: windows
     env:
     - PACKAGE=lib/ftdi

   - stage: "Has first level dependencies"
     env:
     - PACKAGE=tools/fxload

   - stage: "Has first level dependencies"
     env:
     - PACKAGE=tools/dfu-util

   - stage: "Has first level dependencies"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=tools/dfu-util


   - stage: "Has second level dependencies"
     env:
     - PACKAGE=tools/iceprog

   - stage: "Has second level dependencies"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=tools/iceprog

   - stage: "Has second level dependencies"
     os: windows
     env:
     - PACKAGE=tools/iceprog

   - stage: "Has second level dependencies"
     env:
     - PACKAGE=tools/openocd

   - stage: "Has second level dependencies"
     os: osx
     osx_image: xcode8.3
     env:
     - PACKAGE=tools/openocd

  # Move packages from the current label to main
   - stage: "Main label upload"
     os: linux
     dist: xenial
     script:
       - bash $TRAVIS_BUILD_DIR/.travis/master-package.sh

  # Remove old labels
   - stage: "Cleanup"
     os: linux
     dist: xenial
     script:
       - bash $TRAVIS_BUILD_DIR/.travis/cleanup-anaconda.sh

before_install:
 - source $TRAVIS_BUILD_DIR/.travis/common.sh
 - bash $TRAVIS_BUILD_DIR/.travis/fixup-git.sh
 - bash $TRAVIS_BUILD_DIR/.travis/download_sdk.sh
 - source $TRAVIS_BUILD_DIR/.travis/common.sh

install:
 - bash $TRAVIS_BUILD_DIR/.travis/install.sh

script:
 - bash $TRAVIS_BUILD_DIR/.travis/script.sh

after_failure:
 - bash $TRAVIS_BUILD_DIR/.travis/after_failure.sh

after_success:
 - bash $TRAVIS_BUILD_DIR/.travis/after_success.sh

cache:
  directories:
   - $HOME/.conda/pkgs
