name: build-packages
on: [push, pull_request]
env:
  ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
  ANACONDA_USER: ${{ secrets.ANACONDA_USER }}
defaults:
  run:
    shell: bash
jobs:
  libusb-linux:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "lib/usb"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  libxml2-linux:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "lib/xml2"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  icefunprog-linux:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "prog/icefunprog"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  flterm-linux:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "prog/flterm"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  libftdi-linux:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "lib/ftdi"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  fxload-linux:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "prog/fxload"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  dfu-util-linux:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "prog/dfu-util"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  iceprog-linux:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "prog/iceprog"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  openocd-linux:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "prog/iceprog"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  libusb-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "lib/usb"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  libxml2-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "lib/xml2"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  icefunprog-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "prog/icefunprog"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  flterm-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "prog/flterm"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  libftdi-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "lib/ftdi"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  dfu-util-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "prog/dfu-util"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - run: brew install coreutils autoconf automake libtool
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  iceprog-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "prog/iceprog"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  openocd-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "prog/openocd"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - run: brew install coreutils autoconf automake libtool
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  libusb-windows:
    runs-on: "windows-latest"
    env:
      PACKAGE: "lib/usb"
      OS_NAME: "windows"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  libftdi-windows:
    runs-on: "windows-latest"
    env:
      PACKAGE: "lib/ftdi"
      OS_NAME: "windows"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  iceprog-windows:
    runs-on: "windows-latest"
    env:
      PACKAGE: "prog/iceprog"
      OS_NAME: "windows"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  master-package:
    runs-on: "ubuntu-16.04"
    env:
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: urllib3
      - run: |
          bash .github/scripts/install.sh
          python .github/scripts/wait-for-statuses.py
